### ISSUE TITLE
Missing class properties transform 

### ISSUE THREAD

**Issue by undaBen** [bvaughn/react-virtualized-auto-sizer#48] opened 2023-03-31 13:15 UTC
I Guess there is a problem with 1.0.9, this is the error i get when building a project. 
react-virtualized is installed as dependencie to react-map-gl 

```
Failed to compile.

./node_modules/react-virtualized-auto-sizer/dist/react-virtualized-auto-sizer.module.js
SyntaxError: /tmp/cirrusdev/node_modules/react-virtualized-auto-sizer/dist/react-virtualized-auto-sizer.module.js: Missing class properties transform.
  199 |
  200 | class $6e2bb92d9db3b0c8$export$9d94f4ee1d930ff extends (0, $hgUW1$Component) {
> 201 |     static defaultProps = {
      |     ^
  202 |         onResize: ()=>{},
  203 |         disableHeight: false,
  204 |         disableWidth: false,


error Command failed with exit code 1.
```

Best
Ben

**Comment by ofirH08** [comment] 2023-04-02 06:21
We also got this issue

**Comment by orelHAnyvision** [comment] 2023-04-02 09:07
same

**Comment by bvaughn** [comment] 2023-04-02 21:17
Closing as duplicate of #46

**Closed by bvaughn** 2023-04-02 21:17 UTC
